### ISSUE TITLE
Buttons and other components don't work in About Us

### ISSUE THREAD

**Issue by ahfhafh** [duan-le/HackTogether2020#6]
^^ in title

prob something in the head

**Comment by JessieG123** [comment]
The buttons don't work bc they don't have the links to it yet. Right now it just links back to the page itself if you click on the linkedin or github buttons. That what your mean?

**Comment by ahfhafh** [comment]
Nah I mean like when the nav or collapse is implemented the buttons don't work even linked to a page.
I traced it back to one of the head scripts im pretty sure.

**Comment by JessieG123** [comment]
Which buttons are you talking about?
